### ISSUE TITLE
Bonus letters aren't shown when you type in guesses

### ISSUE THREAD

**Issue by samdow** [goffrie/strawberry#24]
Hello! I'm one of Tiffany's friends and we've been playing letterjam a lot!

I noticed that once I've guessed all my letters and am on bonus letters, it doesn't show up in the word anymore. For instance here, 
<img width="501" alt="Screen Shot 2020-05-25 at 9 36 04 PM" src="https://user-images.githubusercontent.com/17888388/83342365-75ec2280-a2a3-11ea-94e6-bb9e75d51326.png">

I would expect the image to be "R (strawberry) ELELE" because I typed in R, which is how it works before I'm on bonus letters (and is personally an awesome feature for visualizing).

Not sure if this is a feature or a bug, but figured I would bring it up! Thanks for helping us get through quarantine

**Comment by goffrie** [comment]
Indeed this is a bug and it annoys me a lot too :)

Maybe I'll fix it one of these days...

**Comment by goffrie** [comment]
OK, hopefully that doesn't break everything. Let me know if things work okay. (You might need to do a force-refresh to get the new code in your browser.)
